### ISSUE TITLE
Suggesting remove an xref is causing counter to be wrong.

### ISSUE THREAD

**Issue by PiotrKozlowski** [openstax-poland/react-counters#2]
### Describe the bug
Suggesting remove an xref is causing counter to be wrong. Video: https://drive.google.com/file/d/144lr3BH1zo1KmZIeDSRnTWhocpICNRc3/view?usp=sharing

### Expected behavior
Counter should not change

## Server
On which server(s) this bug occurs?
- [ ] Staging - https://adaptarr-staging.naukosfera.com
- [ ] Testing - https://adaptarr-testing.naukosfera.org
- [ ] Production - https://adaptarr.naukosfera.com

### Environment:
|**Data type**    |**User input** |
|-----------------|---------------|
|Operating system | [e.g. iOS]    |
|Browser          | [e.g. chrome] |
|Browser version  | [e.g. 22]     |

**Comment by PiotrKozlowski** [comment]
There is a chance that it is related to https://app.zenhub.com/workspaces/adaptarr-5d2f43c60f37561a03177ab7/issues/openstax-poland/adaptarr-front/530

**Comment by MartaSztuka** [comment]
#### PASSED
GIVEN Login to [base-url]
AND Draft in which you have propose changes permissions is open
AND Figure 1 is in the draft
THEN Select Figure 1 
AND Click Backspace
THEN Figure number is red and crossed but counter doesn't change

### SCREENSHOT
![Screenshot from 2021-04-09 13-19-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/26415998-5307-42cc-be4e-a7d8539eb7da)

**Comment by MartaSztuka** [comment]
##### PASSED
https://adaptarr-staging.naukosfera.com/drafts/646663c9-6a5f-463f-91f4-1ee4e0987597/edit
![Screenshot from 2021-06-29 09-26-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fc1348fb-d416-4577-a280-32b3424b8286)
